baseURL = "https://lex00.github.io/wetwire-gcp-go/"
languageCode = "en-us"
title = "Wetwire GCP"

# Theme is added as git submodule in themes/wetwire
theme = "wetwire"

# Clean URLs
[permalinks]
  [permalinks.page]
    '/' = '/:slug/'
  [permalinks.section]
    '/' = '/:slug/'

# Syntax highlighting
[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = false
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Main menu
[menus]
  [[menus.main]]
    name = "CLI"
    pageRef = "/cli"
    weight = 10
  [[menus.main]]
    name = "FAQ"
    pageRef = "/faq"
    weight = 20
  [[menus.main]]
    name = "Lint Rules"
    pageRef = "/lint-rules"
    weight = 30
  [[menus.main]]
    name = "Source"
    url = "https://github.com/lex00/wetwire-gcp-go"
    weight = 50
